#!/usr/bin/env python3
"""
Transformer + VQC Weight Generation — End-to-End Training Example
==================================================================

Demonstrates embedding VQCGeneratedLinear (VQC dynamically generated weights)
into a Transformer FFN, replacing traditional nn.Linear for quantum-classical
hybrid training.

Architecture:
  Input tokens
    → Embedding + Positional Encoding
    → Transformer Encoder × N
        ├── Multi-Head Self-Attention (standard nn.Linear)
        └── FFN:
            ├── nn.Linear(d_model → d_ff)           ← standard linear
            ├── ReLU
            └── VQCGeneratedLinear(d_ff → d_model)   ← VQC generated weights!
    → Classification Head
    → Output

Key design:
  - VQCGeneratedLinear holds a learnable context vector (replaces random features)
  - context → VQC → HyperNetwork dynamically generates weight matrix W
  - Entire pipeline is end-to-end trainable, gradients flow through VQC simulator

Usage:
  # Default hyperparameters
  python transformer_vqc.py

  # Custom hyperparameters
  python transformer_vqc.py --d_model 256 --d_ff 1024 --n_wires 10 --n_qlayers 3

  # Compare with standard Transformer baseline
  python transformer_vqc.py --baseline
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import time
import argparse
import math

from models import VQCGeneratedLinear
from utils import count_parameters

# ============== Random seed ==============
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# ============== Device ==============
if torch.cuda.is_available():
    DEVICE = torch.device("cuda:0")
    print(f"[INFO] CUDA: {torch.cuda.get_device_name(0)}")
else:
    DEVICE = torch.device("cpu")
    print("[INFO] CPU")


# ============================================================================
#  Positional Encoding
# ============================================================================
class PositionalEncoding(nn.Module):
    """Standard sinusoidal positional encoding."""
    def __init__(self, d_model: int, max_len: int = 512, dropout: float = 0.1):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(torch.arange(0, d_model, 2).float()
                             * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0))  # [1, max_len, d_model]

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: [B, seq_len, d_model]
        return self.dropout(x + self.pe[:, :x.size(1), :])


# ============================================================================
#  Transformer Encoder Layer (with VQC FFN)
# ============================================================================
class TransformerEncoderLayer_VQC(nn.Module):
    """
    Transformer Encoder layer: standard Self-Attention + VQC weight-generated FFN.

    FFN structure:
      Linear(d_model → d_ff) → ReLU → VQCGeneratedLinear(d_ff → d_model)
                                     ↑ weights dynamically generated by VQC
    """

    def __init__(self,
                 d_model: int = 128,
                 d_ff: int = 512,
                 n_heads: int = 4,
                 dropout: float = 0.1,
                 # VQC hyperparameters
                 n_wires: int = 10,
                 n_qlayers: int = 2,
                 rank: int = 32,
                 vqc_latent_dim: int = 128,
                 noise_prob: float = 0.0):
        super().__init__()
        # ---- Self-Attention ----
        self.self_attn = nn.MultiheadAttention(
            d_model, n_heads, dropout=dropout, batch_first=True)
        self.norm1 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)

        # ---- FFN (VQC generates second layer weights) ----
        self.ffn_linear1 = nn.Linear(d_model, d_ff)          # standard Linear
        self.ffn_vqc = VQCGeneratedLinear(                    # ★ VQC generated weights
            in_features=d_ff,
            out_features=d_model,
            n_wires=n_wires,
            n_qlayers=n_qlayers,
            rank=rank,
            latent_dim=vqc_latent_dim,
            noise_prob=noise_prob,
            bias=True,
        )
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout2 = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Self-Attention sub-layer
        attn_out, _ = self.self_attn(x, x, x)
        x = self.norm1(x + self.dropout1(attn_out))

        # FFN sub-layer (with VQC generated weights)
        ffn_out = self.ffn_linear1(x)
        ffn_out = F.relu(ffn_out)
        ffn_out = self.ffn_vqc(ffn_out)                       # ★ VQC dynamic weights
        x = self.norm2(x + self.dropout2(ffn_out))
        return x


# ============================================================================
#  Transformer Classifier
# ============================================================================
class TransformerVQCClassifier(nn.Module):
    """
    Transformer sequence classifier with VQC-generated FFN weights.

    Configurable:
      - d_model / d_ff / n_heads / n_layers   (Transformer structure)
      - n_wires / n_qlayers / rank            (VQC structure)
      - num_classes                           (classification classes)
    """

    def __init__(self,
                 vocab_size: int = 1000,
                 d_model: int = 128,
                 d_ff: int = 512,
                 n_heads: int = 4,
                 n_layers: int = 2,
                 max_len: int = 64,
                 num_classes: int = 2,
                 dropout: float = 0.1,
                 # VQC hyperparameters
                 n_wires: int = 10,
                 n_qlayers: int = 2,
                 rank: int = 32,
                 vqc_latent_dim: int = 128,
                 noise_prob: float = 0.0):
        super().__init__()
        self.d_model = d_model

        # Embedding
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoding = PositionalEncoding(d_model, max_len, dropout)

        # Transformer Encoder layers
        self.encoder_layers = nn.ModuleList([
            TransformerEncoderLayer_VQC(
                d_model=d_model, d_ff=d_ff, n_heads=n_heads,
                dropout=dropout, n_wires=n_wires, n_qlayers=n_qlayers,
                rank=rank, vqc_latent_dim=vqc_latent_dim,
                noise_prob=noise_prob,
            )
            for _ in range(n_layers)
        ])

        # Classification Head
        self.cls_head = nn.Sequential(
            nn.Linear(d_model, d_model // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(d_model // 2, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: [B, seq_len]  token indices
        x = self.embedding(x) * math.sqrt(self.d_model)
        x = self.pos_encoding(x)

        for layer in self.encoder_layers:
            x = layer(x)

        # Mean pooling over sequence → classification
        x = x.mean(dim=1)               # [B, d_model]
        return self.cls_head(x)


# ============================================================================
#  Baseline: Standard Transformer (for comparison)
# ============================================================================
class TransformerClassifier(nn.Module):
    """Standard Transformer classifier (all nn.Linear weights), used as baseline."""

    def __init__(self,
                 vocab_size: int = 1000,
                 d_model: int = 128,
                 d_ff: int = 512,
                 n_heads: int = 4,
                 n_layers: int = 2,
                 max_len: int = 64,
                 num_classes: int = 2,
                 dropout: float = 0.1):
        super().__init__()
        self.d_model = d_model
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoding = PositionalEncoding(d_model, max_len, dropout)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=n_heads, dim_feedforward=d_ff,
            dropout=dropout, activation='relu', batch_first=True)
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)

        self.cls_head = nn.Sequential(
            nn.Linear(d_model, d_model // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(d_model // 2, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.embedding(x) * math.sqrt(self.d_model)
        x = self.pos_encoding(x)
        x = self.encoder(x)
        x = x.mean(dim=1)
        return self.cls_head(x)


# ============================================================================
#  Generate synthetic sequence classification data
# ============================================================================
def generate_toy_data(num_samples: int,
                      seq_len: int,
                      vocab_size: int,
                      num_classes: int,
                      device: torch.device):
    """
    Generate synthetic sequence classification data.
    Label is determined by the first two tokens' pattern, making the task learnable.
    """
    x = torch.randint(0, vocab_size, (num_samples, seq_len), device=device)
    # Label determined by first 2 tokens mod (learnable pattern)
    y = ((x[:, 0] + x[:, 1] * 7) % num_classes).long()
    return x, y


# ============================================================================
#  Training & Evaluation
# ============================================================================
def train_one_epoch(model, dataloader, optimizer, criterion, device, desc=""):
    model.train()
    total_loss, total_correct, total_samples = 0.0, 0, 0
    for x_batch, y_batch in dataloader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        logits = model(x_batch)
        loss = criterion(logits, y_batch)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * x_batch.size(0)
        total_correct += (logits.argmax(1) == y_batch).sum().item()
        total_samples += x_batch.size(0)
    return total_loss / total_samples, total_correct / total_samples


@torch.no_grad()
def evaluate(model, dataloader, criterion, device):
    model.eval()
    total_loss, total_correct, total_samples = 0.0, 0, 0
    for x_batch, y_batch in dataloader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)
        logits = model(x_batch)
        loss = criterion(logits, y_batch)
        total_loss += loss.item() * x_batch.size(0)
        total_correct += (logits.argmax(1) == y_batch).sum().item()
        total_samples += x_batch.size(0)
    return total_loss / total_samples, total_correct / total_samples


# ============================================================================
#  Main
# ============================================================================
def parse_args():
    p = argparse.ArgumentParser(
        description="Transformer + VQC Weight Generation — End-to-End Training")
    # Data
    p.add_argument("--vocab_size", type=int, default=1000)
    p.add_argument("--seq_len", type=int, default=32)
    p.add_argument("--num_samples", type=int, default=2000)
    p.add_argument("--num_classes", type=int, default=3)
    # Transformer structure
    p.add_argument("--d_model", type=int, default=128)
    p.add_argument("--d_ff", type=int, default=512)
    p.add_argument("--n_heads", type=int, default=4)
    p.add_argument("--n_layers", type=int, default=2)
    # VQC structure
    p.add_argument("--n_wires", type=int, default=10,
                   help="Number of qubits")
    p.add_argument("--n_qlayers", type=int, default=2,
                   help="VQC variational layers")
    p.add_argument("--rank", type=int, default=32,
                   help="Low-rank decomposition rank")
    p.add_argument("--vqc_latent_dim", type=int, default=128)
    p.add_argument("--noise_prob", type=float, default=0.0)
    # Training
    p.add_argument("--batch_size", type=int, default=32)
    p.add_argument("--epochs", type=int, default=20)
    p.add_argument("--lr", type=float, default=1e-3)
    # Mode
    p.add_argument("--baseline", action="store_true",
                   help="Train standard Transformer as comparison baseline")
    return p.parse_args()


def main():
    args = parse_args()

    print("=" * 65)
    print("  Transformer + VQC Weight Generation — End-to-End Training")
    print("=" * 65)
    print(f"\n[Config]")
    print(f"  Transformer: d_model={args.d_model}  d_ff={args.d_ff}  "
          f"n_heads={args.n_heads}  n_layers={args.n_layers}")
    print(f"  VQC:         n_wires={args.n_wires}  n_qlayers={args.n_qlayers}  "
          f"rank={args.rank}  latent={args.vqc_latent_dim}")
    print(f"  Data:        vocab={args.vocab_size}  seq_len={args.seq_len}  "
          f"samples={args.num_samples}  classes={args.num_classes}")
    print(f"  Training:    epochs={args.epochs}  batch_size={args.batch_size}  "
          f"lr={args.lr}")
    print(f"  Device:      {DEVICE}")

    # ---- Generate data ----
    X, y = generate_toy_data(args.num_samples, args.seq_len,
                             args.vocab_size, args.num_classes, DEVICE)
    split = int(args.num_samples * 0.8)
    train_ds = torch.utils.data.TensorDataset(X[:split], y[:split])
    test_ds = torch.utils.data.TensorDataset(X[split:], y[split:])
    train_loader = torch.utils.data.DataLoader(
        train_ds, batch_size=args.batch_size, shuffle=True)
    test_loader = torch.utils.data.DataLoader(
        test_ds, batch_size=args.batch_size, shuffle=False)

    # ---- Build VQC-Transformer ----
    model_vqc = TransformerVQCClassifier(
        vocab_size=args.vocab_size,
        d_model=args.d_model, d_ff=args.d_ff,
        n_heads=args.n_heads, n_layers=args.n_layers,
        max_len=args.seq_len, num_classes=args.num_classes,
        n_wires=args.n_wires, n_qlayers=args.n_qlayers,
        rank=args.rank, vqc_latent_dim=args.vqc_latent_dim,
        noise_prob=args.noise_prob,
    ).to(DEVICE)

    print(f"\n[VQC-Transformer] Total params: {count_parameters(model_vqc):,}")
    print(f"  VQC variational params + HyperNetwork trained end-to-end via quantum simulator")

    # ---- Train VQC-Transformer ----
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model_vqc.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs)

    print(f"\n{'='*65}")
    print(f"  Training VQC-Transformer ({args.epochs} epochs)")
    print(f"{'='*65}")
    t0 = time.time()
    for epoch in range(args.epochs):
        train_loss, train_acc = train_one_epoch(
            model_vqc, train_loader, optimizer, criterion, DEVICE)
        test_loss, test_acc = evaluate(
            model_vqc, test_loader, criterion, DEVICE)
        scheduler.step()
        print(f"  Epoch {epoch+1:3d}/{args.epochs}  "
              f"train_loss={train_loss:.4f}  train_acc={train_acc:.4f}  "
              f"test_loss={test_loss:.4f}  test_acc={test_acc:.4f}  "
              f"lr={scheduler.get_last_lr()[0]:.2e}")
    t_vqc = time.time() - t0
    print(f"  VQC-Transformer training time: {t_vqc:.2f} s")

    # ---- Final test ----
    _, final_acc = evaluate(model_vqc, test_loader, criterion, DEVICE)
    print(f"\n  ★ VQC-Transformer final test accuracy: {final_acc:.4f}")

    # ---- Baseline comparison ----
    if args.baseline:
        model_baseline = TransformerClassifier(
            vocab_size=args.vocab_size,
            d_model=args.d_model, d_ff=args.d_ff,
            n_heads=args.n_heads, n_layers=args.n_layers,
            max_len=args.seq_len, num_classes=args.num_classes,
        ).to(DEVICE)
        print(f"\n[Standard Transformer] Total params: {count_parameters(model_baseline):,}")

        opt_base = torch.optim.Adam(model_baseline.parameters(), lr=args.lr)
        sched_base = torch.optim.lr_scheduler.CosineAnnealingLR(
            opt_base, T_max=args.epochs)

        print(f"\n{'='*65}")
        print(f"  Training Standard Transformer Baseline ({args.epochs} epochs)")
        print(f"{'='*65}")
        t0 = time.time()
        for epoch in range(args.epochs):
            train_loss, train_acc = train_one_epoch(
                model_baseline, train_loader, opt_base, criterion, DEVICE)
            test_loss, test_acc = evaluate(
                model_baseline, test_loader, criterion, DEVICE)
            sched_base.step()
            print(f"  Epoch {epoch+1:3d}/{args.epochs}  "
                  f"train_loss={train_loss:.4f}  train_acc={train_acc:.4f}  "
                  f"test_loss={test_loss:.4f}  test_acc={test_acc:.4f}")
        t_base = time.time() - t0
        _, base_acc = evaluate(model_baseline, test_loader, criterion, DEVICE)

        print(f"\n  {'='*50}")
        print(f"  Comparison Results:")
        print(f"     VQC-Transformer  accuracy: {final_acc:.4f}  "
              f"time: {t_vqc:.2f}s  params: {count_parameters(model_vqc):,}")
        print(f"     Standard Transformer accuracy: {base_acc:.4f}  "
              f"time: {t_base:.2f}s  params: {count_parameters(model_baseline):,}")
        print(f"  {'='*50}")

    # ---- Save ----
    save_path = "./transformer_vqc.pth"
    torch.save(model_vqc.state_dict(), save_path)
    print(f"\n  Model saved to: {save_path}")
    print(f"\n{'='*65}\n  Done!\n{'='*65}")


if __name__ == "__main__":
    main()
